export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_PROFILES = 'GET_PROFILES';

export const GET_ORDERS = 'GET_ORDERS';
export const ORDERS_ERROR = 'ORDERS_ERROR';

export const DELETE_ORDER = 'DELETE_ORDER';
export const ADD_ORDER = 'ADD_ORDER';


export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const GET_ORDER = 'GET_ORDER';

export const ADD_CONFIRMATION = 'ADD_CONFIRMATION';
export const DELETE_CONFIRMATION = 'ADD_CONFIRMATION';

export const GET_ORDERS_BYUSER_ID = 'GET_ORDERS_BYUSER_ID';

export const GET_PROFILES_BY_CATEGORIES = 'GET_PROFILES_BY_CATEGORIES';







